# Generated by Django 4.0 on 2022-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_pic_vote_ratio_pic_vote_total_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
