# Generated by Django 4.0 on 2022-02-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_pic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
