# Generated by Django 4.0 on 2022-02-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('pic', '0004_alter_pic_id_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
